# Generated by Django 5.1.4 on 2024-12-17 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_room_host"),
        ("rooms", "0002_roomplayer_delete_player"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="roomplayer",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="roomplayer",
            constraint=models.UniqueConstraint(
                fields=("room", "user"), name="unique_user_in_room"
            ),
        ),
        migrations.AddConstraint(
            model_name="roomplayer",
            constraint=models.UniqueConstraint(
                fields=("room", "seat_number"), name="unique_seat_in_room"
            ),
        ),
    ]
