# Generated by Django 5.1.4 on 2024-12-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_alter_roomplayer_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomplayer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="roomplayer",
            name="role",
            field=models.CharField(
                choices=[
                    ("Dealer", "Dealer"),
                    ("Small Blind", "Small Blind"),
                    ("Big Blind", "Big Blind"),
                    ("Player", "Player"),
                ],
                default="Player",
                max_length=20,
            ),
        ),
    ]
