# Generated by Django 5.1.4 on 2024-12-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_roomplayer_is_active_roomplayer_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomplayer",
            name="active_bets",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Активная ставка игрока"
            ),
        ),
    ]
