# Generated by Django 5.1.4 on 2024-12-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0005_roomplayer_active_bets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomplayer",
            name="stack",
            field=models.FloatField(default=0.0),
        ),
    ]
