# Generated by Django 5.1.4 on 2024-12-24 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0006_alter_roomplayer_stack"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roomplayer",
            old_name="active_bets",
            new_name="current_bet",
        ),
    ]
