# Generated by Django 5.1.4 on 2024-12-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_room_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="check_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество чеков"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="current_bet",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Текущая максимальная ставка"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="pot",
            field=models.PositiveIntegerField(default=0, verbose_name="Текущий банк"),
        ),
    ]
