# Generated by Django 5.1.4 on 2024-12-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_room_check_count_room_current_bet_room_pot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="blinds",
        ),
        migrations.AddField(
            model_name="room",
            name="big_blind",
            field=models.PositiveIntegerField(
                default=50, verbose_name="Большой блайнд"
            ),
        ),
    ]
