# Generated by Django 5.1.4 on 2024-12-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_remove_room_blinds_room_big_blind"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="current_player",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Текущий игрок"
            ),
        ),
    ]
