# Generated by Django 5.1.4 on 2024-12-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_room_current_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="pot",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Текущий банк",
            ),
        ),
    ]
