# Generated by Django 5.1.4 on 2024-12-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_room_pot"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="flag_is_started",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="room",
            name="pot",
            field=models.FloatField(default=0.0, verbose_name="Текущий банк"),
        ),
    ]
